### ISSUE TITLE
[Task] Support loading all defined concepts of a namespace

### ISSUE THREAD

**Issue by waltersve** [eclipse-esmf/esmf-sdk-js-aspect-model-loader#19]
**Is your task related to a problem? Please describe.**
Currently the loader allows only to load and single aspect. Better would be to allow to load all defined concepts of a namespace e.g. multiple aspect definitions or definitions which are not directly used within the namespace (intended to be used as a reusable definitions). 

**Describe the solution you'd like**
Load all defined concepts and return ist as a map where the key represents the namespace and the values is an array including all definition as object. This would also allow to load multiple .ttl-files with different namespace.

**Comment by michelu89** [comment]
Is now available on version 2.3.0.
